Repository BuildForSDG/FASTA, pull requests merged in 2020-05, with the labels that each got.

#4 added backend main folder
  fasta-backend/.gitignore
  fasta-backend/app.js
  fasta-backend/bin/www
  fasta-backend/package-lock.json
  fasta-backend/package.json
  fasta-backend/routes/index.js
  fasta-backend/routes/users.js
Labels: enhancement

#13 Ft authenticate and authorization
  .eslintrc.js
  .gitignore
  README.md
  __tests__/app.test.js
  babel.config.js
  fasta-backend/app.js
  fasta-backend/bin/www
  fasta-backend/db/index.js
  fasta-backend/helpers/auth.js
  fasta-backend/middlewares/authChecker.js
  fasta-backend/models/index.js
  fasta-backend/package-lock.json
  fasta-backend/package.json
  fasta-backend/routes/index.js
  fasta-backend/routes/users.js
  jest.config.js
  package-lock.json
Labels: enhancement

#18 feat: implement password reset page
  bash.exe.stackdump
  pages/resetpassword.js
Labels: enhancement

#17 Odunsi/homepage
  components/Homepage/BottomNav.js
  components/Homepage/GPS.js
  components/Homepage/Homepage.js
  components/Homepage/NavBar.js
  components/Homepage/NewReport.js
  components/Homepage/Reports/Report.js
  components/Homepage/Reports/Reports.js
  components/Homepage/Trips/NewTrip.js
  components/Homepage/Trips/RecentTrips.js
  components/Homepage/Trips/Trip.js
  package-lock.json
  package.json
  pages/_app.js
  pages/home.js
  pages/index.js
  public/images/Connector.png
  public/images/Explore-inactive.png
  public/images/Home.png
  public/images/Logo.png
  public/images/More.png
  public/images/Profile-inactive.png
  public/images/Reports-unactive.png
  public/images/alert.png
  webpack.config.js
Labels: enhancement

#54 feat: configure app.properties file
  app.properties
Labels: enhancement

#59 Update App.properties to match New tempalte
  .editorconfig
  .eslintignore
  .eslintrc.js
  .gitignore
  .npmignore
  .prettierrc
  LICENSE
  README.md
  __tests__/app.test.js
  app.properties
  babel.config.js
  fasta-backend/.gitignore
  fasta-backend/api/transporters-api.js
  fasta-backend/app.js
  fasta-backend/bin/www
  fasta-backend/db/index.js
  fasta-backend/helpers/auth.js
  fasta-backend/helpers/mailer.js
  fasta-backend/middlewares/authChecker.js
  fasta-backend/models/index.js
  fasta-backend/models/report.js
  fasta-backend/package-lock.json
  fasta-backend/package.json
  fasta-backend/routes/index.js
  fasta-backend/routes/location-transporter.js
  fasta-backend/routes/report.js
  fasta-backend/routes/sendmail.js
  fasta-backend/routes/users.js
  jest.config.js
  package-lock.json
  package.json
  yarn.lock
Labels: documentation

#57 feat: integration of front&back ends
  components/Account/account.js
  components/Account/style.js
  components/Buttons.js
  components/Homepage/BottomNav.js
  components/Homepage/GPS.js
  components/Homepage/NavBar.js
  components/Homepage/Reports/Reports.js
  components/Homepage/Trips/NewTrip.js
  components/Homepage/Trips/RecentTrips.js
  components/OnBoardingLayout/Layout.js
  components/Text/Body.js
  components/Text/Headings.js
  pages/_document.js
  pages/account.js
  pages/changepassword.js
  pages/home.js
  pages/login.js
  pages/resetpassword.js
  pages/signup.js
Labels: bug, work-in-progress

#56 Ft front end reports
  components/BottomNav.js
  components/Buttons.js
  components/Cards/ReportCard.js
  components/Header.js
  components/Homepage/Homepage.js
  components/Homepage/NewReport.js
  components/Input.js
  components/Layout.js
  package.json
  pages/_app.js
  pages/_document.js
  pages/home.js
  pages/login.js
  pages/report.js
  pages/reports/[id].js
  pages/reports/makeReport.js
  pages/signup.js
  public/images/Back-Arrow-Black.svg
  public/images/Explore-active.svg
  public/images/Home-inactive.svg
  public/images/Profile-active.svg
  public/images/Reports-active.svg
  public/images/Reports-inactive.png
  public/images/ic_file_new.svg
  tailwind.config.js
Labels: enhancement
